### ISSUE TITLE
Creation de la vue par defaut

### ISSUE THREAD

**Issue by zaclimon** [ApplETS/Notre-Dame-iOS#1]
- [x] Création de la barre de navigation inférieure
- [x] Ajout des sections dans la barre de navigation
- [x] Changement des sections en fonction de la sélection de la barre

**Comment by kovy42** [comment]
Le bottom menu est déjà fonctionnel, qu'est-ce qu'il manquerait pour fermer l'issue?

**Comment by zaclimon** [comment]
Yep it's all good, my bad et beau boulôt! 👍
