### ISSUE TITLE
Urgences: Vue d'un type d'urgence particulier

### ISSUE THREAD

**Issue by zaclimon** [ApplETS/Notre-Dame-iOS#4]
Manière de représenter les urgences lorsque dans une section. Entre autres:

- [x] Format (HTML, PDF, Texte brut, etc...)
- [x] Mise en page
- [x] Liens pour contact immédiat (Téléphone, courriel)

**Comment by zaclimon** [comment]
@kovy42 Je me rapelle que tu avais dit que tu allais faire le layout en natif mais est-ce qu'il serait possible d'obtenir un screenshot pour une section donnée?

**Comment by kovy42** [comment]
![simulator screen shot - iphone se - 2018-06-06 at 21 41 12](https://user-images.githubusercontent.com/25484259/41073686-7b6657aa-69d2-11e8-870c-4203bd287a0d.png)

**Comment by zaclimon** [comment]
Bon on peut s'en tenir à ça pour le moment et voir lorsqu'on aura des designs un peu plus complet à ce niveau. Closed.
