### ISSUE TITLE
Localisation en anglais pour les urgences actuels

### ISSUE THREAD

**Issue by zaclimon** [ApplETS/Notre-Dame-iOS#8]
Documentation pour la localisation:
https://medium.com/lean-localization/ios-localization-tutorial-938231f9f881

- [x] Créer un fichier .ljproj pour l'application
- [x] Ajuster le texte dans les croquis actuels

**Comment by kovy42** [comment]
Les fichiers de localisation (en.lproj, fr.lproj) ont été créés. Il reste à associer les labels aux variables, puis à en traduire le contenu dans les fichiers de localisation.

**Comment by zaclimon** [comment]
My bad j'avais mal fait les checkboxes. :joy: Ils sont clickables maintenant! (Unrelated mais bon)

**Comment by zaclimon** [comment]
Terminé donc fermons ça. Nice job en passant @kovy42 :+1:
